before_script:
  - echo "Before script"
  - cd /var/www/api.devopsethis.com
building:
  stage: build
  only:
    - staging-new
  script:
    # - git reset --hard
    - git pull origin3 staging-new
    - composer install
    # - cp .env.example .env
    # - php artisan key:generate
    - php artisan migrate
    - php artisan cache:clear
    - php artisan config:clear
    - php artisan storage:link
    - sudo chown -R www-data:www-data /var/www/api.devopsethis.com/
    - find /var/www/api.devopsethis.com -type f -exec chmod 664 {} \;
    - find /var/www/api.devopsethis.com -type d -exec chmod 775 {} \;
    - chgrp -R www-data storage bootstrap/cache
    - chmod -R ug+rwx storage bootstrap/cache
# testing:
#   stage: test
#   script:
#     - php ./vendor/bin/phpunit
deploying:
  stage: deploy
  script:
    - echo "Deployed"
  only:
    - staging-new
  except:
    - master
